hash-format = "sha256"

[[files]]
file = ".git/COMMIT_EDITMSG"
hash = "8d74beec1be996322ad76813bafb92d40839895d6dd7ee808b17ca201eac98be"

[[files]]
file = ".git/FETCH_HEAD"
hash = "0344190e144d93a989108074c6bcd292e1e4bbe0949d1dce94ce36fee7cbb4fb"

[[files]]
file = ".git/HEAD"
hash = "28d25bf82af4c0e2b72f50959b2beb859e3e60b9630a5e8c603dad4ddb2b6e80"

[[files]]
file = ".git/config"
hash = "8c5ba278a87955cf6c1ff7f2fb28c07a4f92e91690b38cb2fc6f0cd87d0244ad"

[[files]]
file = ".git/description"
hash = "6ca5fb92618a1370066b2e4f53bf9e6736ff1219827c1ec0f4d3ea3a60e86930"

[[files]]
file = ".git/hooks/applypatch-msg.sample"
hash = "0223497a0b8b033aa58a3a521b8629869386cf7ab0e2f101963d328aa62193f7"

[[files]]
file = ".git/hooks/commit-msg.sample"
hash = "1f74d5e9292979b573ebd59741d46cb93ff391acdd083d340b94370753d92437"

[[files]]
file = ".git/hooks/fsmonitor-watchman.sample"
hash = "f3c0228d8e827f1c5260ac59fdd92c3d425c46e54711ef713c5a54ae0a4db2b4"

[[files]]
file = ".git/hooks/post-update.sample"
hash = "81765af2daef323061dcbc5e61fc16481cb74b3bac9ad8a174b186523586f6c5"

[[files]]
file = ".git/hooks/pre-applypatch.sample"
hash = "e15c5b469ea3e0a695bea6f2c82bcf8e62821074939ddd85b77e0007ff165475"

[[files]]
file = ".git/hooks/pre-commit.sample"
hash = "f9af7d95eb1231ecf2eba9770fedfa8d4797a12b02d7240e98d568201251244a"

[[files]]
file = ".git/hooks/pre-merge-commit.sample"
hash = "d3825a70337940ebbd0a5c072984e13245920cdf8898bd225c8d27a6dfc9cb53"

[[files]]
file = ".git/hooks/pre-push.sample"
hash = "ecce9c7e04d3f5dd9d8ada81753dd1d549a9634b26770042b58dda00217d086a"

[[files]]
file = ".git/hooks/pre-rebase.sample"
hash = "4febce867790052338076f4e66cc47efb14879d18097d1d61c8261859eaaa7b3"

[[files]]
file = ".git/hooks/pre-receive.sample"
hash = "a4c3d2b9c7bb3fd8d1441c31bd4ee71a595d66b44fcf49ddb310252320169989"

[[files]]
file = ".git/hooks/prepare-commit-msg.sample"
hash = "e9ddcaa4189fddd25ed97fc8c789eca7b6ca16390b2392ae3276f0c8e1aa4619"

[[files]]
file = ".git/hooks/push-to-checkout.sample"
hash = "a53d0741798b287c6dd7afa64aee473f305e65d3f49463bb9d7408ec3b12bf5f"

[[files]]
file = ".git/hooks/update.sample"
hash = "8d5f2fa83e103cf08b57eaa67521df9194f45cbdbcb37da52ad586097a14d106"

[[files]]
file = ".git/index"
hash = "fa31c219c6b57edbf8a8a1bcd8aa843bf8dcc6c9314872013015b432b308d335"

[[files]]
file = ".git/info/exclude"
hash = "6671fe83b7a07c8932ee89164d1f2793b2318058eb8b98dc5c06ee0a5a3b0ec1"

[[files]]
file = ".git/logs/HEAD"
hash = "4f28ed11b404ad3883ffb9e1cd16eac7c46facfc07c4e223fec241794cd7eb3b"

[[files]]
file = ".git/logs/refs/heads/main"
hash = "4f28ed11b404ad3883ffb9e1cd16eac7c46facfc07c4e223fec241794cd7eb3b"

[[files]]
file = ".git/logs/refs/remotes/origin/main"
hash = "56b4381ba842011002d3acc3cbb9a73bd4fa188e610989d51c53ed2eacb78ed9"

[[files]]
file = ".git/objects/07/f02ff8fb95e9f1ce5b47311a2e1c6cf904f188"
hash = "7f928fd298b1825bd9ab9ea76164c8e5de010de43b04a0cc5a91a4c8eeb62cc2"

[[files]]
file = ".git/objects/48/d22401774c17908478511ea38cb82072400046"
hash = "3a2e1db2507b801a1dfea15849eca8b5aa1e9d6eab829989c80621673fc7f071"

[[files]]
file = ".git/objects/6f/9509c88bed7080d496fc5e1d87a9315e30549d"
hash = "b997ea11414db588856ded0346306cf4b8334aedd7e40aea0758f4d5ddafb448"

[[files]]
file = ".git/objects/73/51f3cc4cba1b5ebae0e36b7d83231fe30ae69e"
hash = "2575aff63de4f02abe8fbecedbde4357fb93c2f4d26a07c381a221f842194e88"

[[files]]
file = ".git/objects/84/acba97b5626a50ddca1a37f0406567ece98ae5"
hash = "ccf41cfccfa5fbfc7516089cd57d4cc100300579a2201a7858ca49316a86c3ab"

[[files]]
file = ".git/objects/ce/2df7b1bcae5627a7744be7a5a13e75dab5a4ff"
hash = "e998509fd9a7c62f6c2228cd14926fb1bd64b5cfc56c9890f9564900ce301626"

[[files]]
file = ".git/objects/df/e0770424b2a19faf507a501ebfc23be8f54e7b"
hash = "bc2765c7012275e921f22fb94d53158122c693d0cf6426406d6aaf19848a43d7"

[[files]]
file = ".git/refs/heads/main"
hash = "6fff22571b63560b8ae0c25ff31d525de420e0d2cef9aa4ab21ac79fd6812c8e"

[[files]]
file = ".git/refs/remotes/origin/main"
hash = "6fff22571b63560b8ae0c25ff31d525de420e0d2cef9aa4ab21ac79fd6812c8e"

[[files]]
file = ".gitattributes"
hash = "1a1dbe176bc233b499d35a57db7513f2941c99ab9759f177830c9149be99005b"
