hash-format = "sha256"

[[files]]
file = "mods/cit-resewn.toml"
hash = "4bb58d967d9a940a6fba0e9155dbce5e4deed6a86ead3f913648ed64be570162"
metafile = true

[[files]]
file = "mods/custom-lan.toml"
hash = "3d1ae3b20ccd3ace88c82d1a6b33d98f3be4bb1ce9a818c5870902db3d573ba0"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "8f7148ddea91eb8e149e84a07d378d4c0cf12223ca12689036a600672bd24554"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "51459057d731fd7508b48ab92ced48499346ec712b9c8d4f6eebe20c9dc2651c"
metafile = true

[[files]]
file = "mods/kappa.toml"
hash = "4ad083e59a3afc403f0cbb29715aec65d5d7556f157419127ee17913b817192f"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "ffa430c24d8d6862b804c483a9070340fd3a89f858f8a5869b715534a06a04de"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/plasmo-voice.toml"
hash = "df4c27923d2f359972dd4cc963e4d5af9c8371b8bca6c0260427de7e4857c037"
metafile = true

[[files]]
file = "mods/tiefix.toml"
hash = "72a0c1c7bd0e17a7d31e7aaf6beaad2ba959353c9cbafef77844952ba6b5b753"
metafile = true
