hash-format = "sha256"

[[files]]
file = "mods/iris.toml"
hash = "92eab931314c02773c8466741e070791a94ade517298b49441b116e1c2da2a94"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "55f39b31f37997e41e0578693103e50cebc79d4eee509801479cc50a75eeb347"
metafile = true
