hash-format = "sha256"

[[files]]
file = "mods/cem.toml"
hash = "84736dff13eb506b1cedcdb7a359bb0af143b987696e382e7502591d51c65ac2"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "662c4290b6cb893f17754badc199be1069f435e3fda28ee4aed876892a465162"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "4d3086d640c86bf3625ce9067d02d9ed586d23ff6bd3398655fd2fbfdce83de6"
metafile = true

[[files]]
file = "mods/custom-lan.toml"
hash = "3d1ae3b20ccd3ace88c82d1a6b33d98f3be4bb1ce9a818c5870902db3d573ba0"
metafile = true

[[files]]
file = "mods/ebe.toml"
hash = "c58834af10ab46edeb4946b55f4d71cf9bced4d37aef0ee122a5a7e4e9e17153"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "fbbd1baff071a77e7a9bd82c99573bcb8ad793adf9b4fb31b35f16c38cc20ce8"
metafile = true

[[files]]
file = "mods/gldown.toml"
hash = "2c427789543f276864e54ae8fbfcb58c09b67b19fae65eb36e19381c956df84b"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "177d9e7706d685b7d8b8f964702aac4f9bd080687ee1496fc289f295056b8a23"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "3454bf031fe62a04f108377c719ae79ba410787296a3e0cd61eca7c919e60fe1"
metafile = true

[[files]]
file = "mods/kappa.toml"
hash = "6363596c5cb5959ee0905e42c305b27934f169e634eaffc6ca268623c2410915"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "ffa430c24d8d6862b804c483a9070340fd3a89f858f8a5869b715534a06a04de"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "490cf7564c6825e36933785196a6302c58f9d2658f60e2d2fb1f85ed112e36d1"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "b5e2c3c08224e46e840c739f0b77bb22949373cc76d0ba90ddb22e52ecaa04c7"
metafile = true

[[files]]
file = "mods/plasmo-voice.toml"
hash = "88434fbde54b61254d3d0adea22de30f5c3660163a44ec7fdf64a1c2c2be4811"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "1f04100ac9ec2dd3d54ad14b91fe5421549704f40e5a8447f842195a041facd8"
metafile = true

[[files]]
file = "mods/tiefix.toml"
hash = "90bc891202a1ab6fcdaa8833f9482f918887dcf9829aaf21505578d00583bc79"
metafile = true
