hash-format = "sha256"

[[files]]
file = "mods/cem.toml"
hash = "84736dff13eb506b1cedcdb7a359bb0af143b987696e382e7502591d51c65ac2"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "4c4a87a05ed89f6a0a99b2783c9c4e9dfdaef462fed8ff88bd73d27da73d4ed5"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "4d3086d640c86bf3625ce9067d02d9ed586d23ff6bd3398655fd2fbfdce83de6"
metafile = true

[[files]]
file = "mods/custom-lan.toml"
hash = "3d1ae3b20ccd3ace88c82d1a6b33d98f3be4bb1ce9a818c5870902db3d573ba0"
metafile = true

[[files]]
file = "mods/ebe.toml"
hash = "c58834af10ab46edeb4946b55f4d71cf9bced4d37aef0ee122a5a7e4e9e17153"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "da62be08037c326851ea1443be7532120dc09b24aac93144120126717d6813d1"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "3590b0046a05328fa8f4f3d499be14514002d8658879b600b5e2a46f60f85783"
metafile = true

[[files]]
file = "mods/gldown.toml"
hash = "2c427789543f276864e54ae8fbfcb58c09b67b19fae65eb36e19381c956df84b"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "89f5ed5d28ea532046afeb96cb51ec7e450729e2e201011706cc0612a7d18c49"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "86de763b5496190c776b15871c109ecddf64f4a8f9c2d611e689d9976dd359e3"
metafile = true

[[files]]
file = "mods/kappa.toml"
hash = "6363596c5cb5959ee0905e42c305b27934f169e634eaffc6ca268623c2410915"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "ffa430c24d8d6862b804c483a9070340fd3a89f858f8a5869b715534a06a04de"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "490cf7564c6825e36933785196a6302c58f9d2658f60e2d2fb1f85ed112e36d1"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "b5e2c3c08224e46e840c739f0b77bb22949373cc76d0ba90ddb22e52ecaa04c7"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "1f04100ac9ec2dd3d54ad14b91fe5421549704f40e5a8447f842195a041facd8"
metafile = true

[[files]]
file = "mods/tiefix.toml"
hash = "26d2dc9abe46668f6b884bde739d0faae776b956e87f2c13f253fdf1aa919083"
metafile = true
