hash-format = "sha256"

[[files]]
file = "mods/bedrockskinutility.toml"
hash = "ead1756eb3ac87a7689a6abc45e99fa9da82c09dedb29a0becb00c0d67b9987c"
metafile = true

[[files]]
file = "mods/cem.toml"
hash = "84736dff13eb506b1cedcdb7a359bb0af143b987696e382e7502591d51c65ac2"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "4c4a87a05ed89f6a0a99b2783c9c4e9dfdaef462fed8ff88bd73d27da73d4ed5"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "006a14c972eaeaea050b9e4e0d024f8782c2fe44e5f7a502eb392e9aa7793bae"
metafile = true

[[files]]
file = "mods/ebe.toml"
hash = "c58834af10ab46edeb4946b55f4d71cf9bced4d37aef0ee122a5a7e4e9e17153"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "02f05c1580b70e3cfcd029a0b7ed57657cbfceab80224ebe27e0be09a369ffce"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "3590b0046a05328fa8f4f3d499be14514002d8658879b600b5e2a46f60f85783"
metafile = true

[[files]]
file = "mods/gldown.toml"
hash = "2c427789543f276864e54ae8fbfcb58c09b67b19fae65eb36e19381c956df84b"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "7215a34a544194eecb37e9bdfd9664edf21ac991f5a7b19c661e033975fe735f"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "329ad4202e00111815c4dd7121a667019eadfbdabcf9371f952f5a16b2098cb2"
metafile = true

[[files]]
file = "mods/kappa.toml"
hash = "6363596c5cb5959ee0905e42c305b27934f169e634eaffc6ca268623c2410915"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "492ccef1b220ed135344c864959b560fcedb53a40d2c828af92c2ad59d873512"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "64a4b886ff13e45a06ae3714f4ec3fd5c15a1a4e0573df1cdfa35d673eec45ad"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "b5e2c3c08224e46e840c739f0b77bb22949373cc76d0ba90ddb22e52ecaa04c7"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "0c83c344046d0b96fd7dcd9e5c98c44caa3d307126d502f202dba50855304fb9"
metafile = true

[[files]]
file = "mods/tiefix.toml"
hash = "26d2dc9abe46668f6b884bde739d0faae776b956e87f2c13f253fdf1aa919083"
metafile = true
