hash-format = "sha256"

[[files]]
file = ".git/COMMIT_EDITMSG"
hash = "2619be9dc0356a196a8743f1f8eccfab471ac9f3e38f0c87f5bb052339f196a2"

[[files]]
file = ".git/FETCH_HEAD"
hash = "d6df6dd2861f57ab524e11f297fa1b6883de4fa4063094a1606d9a1649ddcc55"

[[files]]
file = ".git/HEAD"
hash = "28d25bf82af4c0e2b72f50959b2beb859e3e60b9630a5e8c603dad4ddb2b6e80"

[[files]]
file = ".git/config"
hash = "8c5ba278a87955cf6c1ff7f2fb28c07a4f92e91690b38cb2fc6f0cd87d0244ad"

[[files]]
file = ".git/description"
hash = "6ca5fb92618a1370066b2e4f53bf9e6736ff1219827c1ec0f4d3ea3a60e86930"

[[files]]
file = ".git/hooks/applypatch-msg.sample"
hash = "0223497a0b8b033aa58a3a521b8629869386cf7ab0e2f101963d328aa62193f7"

[[files]]
file = ".git/hooks/commit-msg.sample"
hash = "1f74d5e9292979b573ebd59741d46cb93ff391acdd083d340b94370753d92437"

[[files]]
file = ".git/hooks/fsmonitor-watchman.sample"
hash = "f3c0228d8e827f1c5260ac59fdd92c3d425c46e54711ef713c5a54ae0a4db2b4"

[[files]]
file = ".git/hooks/post-update.sample"
hash = "81765af2daef323061dcbc5e61fc16481cb74b3bac9ad8a174b186523586f6c5"

[[files]]
file = ".git/hooks/pre-applypatch.sample"
hash = "e15c5b469ea3e0a695bea6f2c82bcf8e62821074939ddd85b77e0007ff165475"

[[files]]
file = ".git/hooks/pre-commit.sample"
hash = "f9af7d95eb1231ecf2eba9770fedfa8d4797a12b02d7240e98d568201251244a"

[[files]]
file = ".git/hooks/pre-merge-commit.sample"
hash = "d3825a70337940ebbd0a5c072984e13245920cdf8898bd225c8d27a6dfc9cb53"

[[files]]
file = ".git/hooks/pre-push.sample"
hash = "ecce9c7e04d3f5dd9d8ada81753dd1d549a9634b26770042b58dda00217d086a"

[[files]]
file = ".git/hooks/pre-rebase.sample"
hash = "4febce867790052338076f4e66cc47efb14879d18097d1d61c8261859eaaa7b3"

[[files]]
file = ".git/hooks/pre-receive.sample"
hash = "a4c3d2b9c7bb3fd8d1441c31bd4ee71a595d66b44fcf49ddb310252320169989"

[[files]]
file = ".git/hooks/prepare-commit-msg.sample"
hash = "e9ddcaa4189fddd25ed97fc8c789eca7b6ca16390b2392ae3276f0c8e1aa4619"

[[files]]
file = ".git/hooks/push-to-checkout.sample"
hash = "a53d0741798b287c6dd7afa64aee473f305e65d3f49463bb9d7408ec3b12bf5f"

[[files]]
file = ".git/hooks/update.sample"
hash = "8d5f2fa83e103cf08b57eaa67521df9194f45cbdbcb37da52ad586097a14d106"

[[files]]
file = ".git/index"
hash = "5924c4a9ccca419dfe19e2d82f3cac4c8065abd1afc723ba3eaf480396f8e11f"

[[files]]
file = ".git/info/exclude"
hash = "6671fe83b7a07c8932ee89164d1f2793b2318058eb8b98dc5c06ee0a5a3b0ec1"

[[files]]
file = ".git/logs/HEAD"
hash = "91abf15659a5cfc25a68eb8fa84e634cc2733c3aa7e5b7c576757b6a33dc6f39"

[[files]]
file = ".git/logs/refs/heads/main"
hash = "91abf15659a5cfc25a68eb8fa84e634cc2733c3aa7e5b7c576757b6a33dc6f39"

[[files]]
file = ".git/logs/refs/remotes/origin/main"
hash = "d5abef66c51b75797f45767b99bad06c0bbfbfea91fcada0d3c84504226f1fb1"

[[files]]
file = ".git/objects/07/f02ff8fb95e9f1ce5b47311a2e1c6cf904f188"
hash = "7f928fd298b1825bd9ab9ea76164c8e5de010de43b04a0cc5a91a4c8eeb62cc2"

[[files]]
file = ".git/objects/0f/fa4f03d1ff943611215f4e89179e8f8b820b0e"
hash = "09fdfffada69dc2a8f3d51d20bf7747a85200d2dbe158766b3a11d6fe34b3fe3"

[[files]]
file = ".git/objects/17/ebda7c5fdfef316cdaa6785f336dc01667253c"
hash = "2bf649a34dac15e250517512682f71524b908c6768464ebcd0763540ca5e8a28"

[[files]]
file = ".git/objects/1d/3d07c0fced17aed234a8f4ebf5074e5dbf00a6"
hash = "d34cd9aee357bc40f3163a6387fb09fc7cb528d7063976cd63283b119b740302"

[[files]]
file = ".git/objects/22/f00b60698c2d162cb83e627c4bba69270e8662"
hash = "6feae3878f8b77600f2d641bba8fbe9a2ab078078d1e49a276520ef0cf4814ed"

[[files]]
file = ".git/objects/26/7bc00aae506066a054c1eaa02719d589e0d485"
hash = "1cf1d39b6ea5a784daab114afc0d4883507988aa5d5eec42ccb76ba12312db0f"

[[files]]
file = ".git/objects/2c/c840da58620d365fcd834e7a5a37fa4b9cc383"
hash = "362cc290a61339629ae6e300ba2919522dfc9d5a78a080d89cbbadf502f7b3a2"

[[files]]
file = ".git/objects/33/047568d80f6bb36d83bcabd1f1f2ab8428c4e5"
hash = "ec7af3dffde253e41ce5d33a66efa97efc92ac185c785b02aa601213009152b4"

[[files]]
file = ".git/objects/38/0cec23c154feed03fb8ca2edc80eb3ae7f22bc"
hash = "4193d6a06d0e88eff1e20558570e4c34232d72d81ff6d30b1ef099a7336caffd"

[[files]]
file = ".git/objects/3c/fc23e5e1a00e98bb2f11ccc3cbde8ff3797be0"
hash = "cf6725999a6d269964a14275a5cc9c7584b2408c34d8b8a7755d14fba536bc13"

[[files]]
file = ".git/objects/43/3ec24b2a266d575d1efd518796b5c9cce61092"
hash = "73867c7517bee61345b2d647c02b85a2605fa604acc9fde5e57f268e59ecd2fa"

[[files]]
file = ".git/objects/48/cd13104393f3003e454051eb0c6316787d980c"
hash = "e7fe120cb6afac956177d7d83517cea9b7e9f06d48bc58a43fae269f8e9b50b7"

[[files]]
file = ".git/objects/48/d22401774c17908478511ea38cb82072400046"
hash = "3a2e1db2507b801a1dfea15849eca8b5aa1e9d6eab829989c80621673fc7f071"

[[files]]
file = ".git/objects/4f/a302548f44421f6d64c14c3b27749a168c92bd"
hash = "f772cd060504d2da5666169b8b4df08592bab17606cd6a2b1f2a38730e50bafa"

[[files]]
file = ".git/objects/52/b163c84ed7021dc4dd709b6d7be68aa1051cfb"
hash = "99c7360df131e926ba8cd5a25cab7d3d38882887ba0926dc4d967083b564f04f"

[[files]]
file = ".git/objects/6f/9509c88bed7080d496fc5e1d87a9315e30549d"
hash = "b997ea11414db588856ded0346306cf4b8334aedd7e40aea0758f4d5ddafb448"

[[files]]
file = ".git/objects/73/2a3dbe8a842d5e692b099b7e365bfab80d3822"
hash = "ba4d5662aa68df79a3e7db276f59673a65a3b291e82f6d744daf7686f3063fcd"

[[files]]
file = ".git/objects/73/51f3cc4cba1b5ebae0e36b7d83231fe30ae69e"
hash = "2575aff63de4f02abe8fbecedbde4357fb93c2f4d26a07c381a221f842194e88"

[[files]]
file = ".git/objects/74/c4e9fe54293585dc47ca3a2a06128110601444"
hash = "f6f63e8617d0e42debf1e9ae28e70a3aab58ea190d1f039baf6ef3c08f3774e1"

[[files]]
file = ".git/objects/7f/dc4735309d6c079710d55ca5deda8fa7b92d90"
hash = "7a9c78fbdb14f8aa71a0671daa3e9c4249a9b81ade480b7d5662654cbd4e831f"

[[files]]
file = ".git/objects/81/90145f97b6715e9e32e86d525bec1ab582715f"
hash = "7cf9612463fb7bd088d53aabff0207fd427f442cd94092ff7ac2eeb70b2fafb0"

[[files]]
file = ".git/objects/84/acba97b5626a50ddca1a37f0406567ece98ae5"
hash = "ccf41cfccfa5fbfc7516089cd57d4cc100300579a2201a7858ca49316a86c3ab"

[[files]]
file = ".git/objects/88/f86de48d25a1b39285aa054d4fd98cdb2ad8d0"
hash = "cd67971a1af7961611fa4d40ca95826457ebb3076f3b3662ee0989e63aba36a9"

[[files]]
file = ".git/objects/8a/be5c2bdcdbc1b453d6899a7b682aa904bafcab"
hash = "64c081710bf7762dfc2d0ea83cee1dfcf496d590edaf1378ca10525574ffcd12"

[[files]]
file = ".git/objects/8b/462386581a6b0c368dde138100562822f48056"
hash = "923f2ea23f808ffa635f34ce7fdf628adf639bd74bf11f7d2ee089feefcd13fc"

[[files]]
file = ".git/objects/91/037d3b2b76913edfb765e405c153d18c0e2a41"
hash = "f3ddadc7a67442a311fa46aa94d1f4bc9a7901d7c14d499e8dfbe5d05fac7f1b"

[[files]]
file = ".git/objects/96/fd7ace8f172b3937c96a121af224d746b3b0e6"
hash = "bdf1a8fa65ed25fe14fc4beec8e80cb528ba45e75280ffd1afc5098a0737cf9b"

[[files]]
file = ".git/objects/9b/5481ba298fde5be16a821a7350c37905776238"
hash = "6492d1e534fc8094f6b9f1c10d6d46b231e7cdaa6e0fca89491a83a0133ac104"

[[files]]
file = ".git/objects/ae/260aebe0b4d0230ccf0c6c23074ae16c980236"
hash = "d71711b480e46b5c1bf556fc91f833d51f5f15de9210df3a89b5e1c2619117da"

[[files]]
file = ".git/objects/ae/9e41b83f36c9964460c3b2797fec7be330abab"
hash = "fb45c01ca223842d25d2c1288dab11a55fa9ae691ce7f824e94480482e2a1d3f"

[[files]]
file = ".git/objects/b2/8683cbfc14b390d5f24dcaba0d30bbdea742d2"
hash = "e4e0518c3e07b1ffa103d1b5e772f056b721215beced2de9211753284ba278c7"

[[files]]
file = ".git/objects/b5/baa1cffb307affb1ba737cd078f67726cb5b23"
hash = "7a806147bc25652d88fbf9cc653d44629afbaf1448de0bd7ab629a4c43187f3a"

[[files]]
file = ".git/objects/c2/4d53ba9f1afc5592cf2cdc726010d999edc864"
hash = "d27330f78f2c9d92641dc0addcbdc45279de056501ffac9f2aa941bd8eee6338"

[[files]]
file = ".git/objects/c6/11c10d6db596f2370945704d3a8f150746bf1d"
hash = "8ff27bb379aa66b710eaccdaf43cff363c9cf83d7772277270e81bc76a9f8705"

[[files]]
file = ".git/objects/c6/6e4bd76ab9aa19062d5cfafdeb63bd56ab8ba5"
hash = "8d8af33fdff3c83e9a7dc777b4eec96d1950a5fc37a52e13f010819604805b38"

[[files]]
file = ".git/objects/c8/5010ae8799862f037a219415587bc5a75112a4"
hash = "90bd37dbd7d5c31a8c1d1a42761ed1e7c0d6aca953041134be61d4321f6d6201"

[[files]]
file = ".git/objects/c9/a8d2f8b7b80c54f6f3de0a15e11bcf9dca340a"
hash = "598c81613eb63a8c48977b0a338138a5f0d8884c0a41b876ce62e567f14dba70"

[[files]]
file = ".git/objects/ce/2df7b1bcae5627a7744be7a5a13e75dab5a4ff"
hash = "e998509fd9a7c62f6c2228cd14926fb1bd64b5cfc56c9890f9564900ce301626"

[[files]]
file = ".git/objects/d8/fbcb71a0edd2b10fbb14a1da6d305db4a197c5"
hash = "7a9a46cec8633555348b4d7b0c90de1bdeea28f756a5059adcce5f61cc088597"

[[files]]
file = ".git/objects/df/e0770424b2a19faf507a501ebfc23be8f54e7b"
hash = "bc2765c7012275e921f22fb94d53158122c693d0cf6426406d6aaf19848a43d7"

[[files]]
file = ".git/objects/e4/0f462e1d0eafe8675dc2300c628b8364c3889a"
hash = "a316875401905d5932b13afc90d44b49160d1d873b06207b844999122525fdf3"

[[files]]
file = ".git/objects/eb/99f13870a4c5df391f4ac5f5f366cbdce490ae"
hash = "4826120f249bc525d886bf360fecb8c4f19187b7f5d44c5995dfdfd6aaae9449"

[[files]]
file = ".git/objects/f6/c2d9316cea2de06ad7da7aaf329ca2a38b9764"
hash = "c97b17c7949a676b3be6ca0a512f8e42ab7b308dc2a97ebe5e603c6742928f1e"

[[files]]
file = ".git/refs/heads/main"
hash = "faefb9fd596a02d0b1db2db43dad59263b0bcf0abdbc6f39ff5d6e78c1b86a4e"

[[files]]
file = ".git/refs/remotes/origin/main"
hash = "faefb9fd596a02d0b1db2db43dad59263b0bcf0abdbc6f39ff5d6e78c1b86a4e"

[[files]]
file = ".gitattributes"
hash = "1a1dbe176bc233b499d35a57db7513f2941c99ab9759f177830c9149be99005b"

[[files]]
file = "mods/animatica.toml"
hash = "0f832605c4764af1bf759fd26fb11bbe23b9eb3580f75a8999d5431a0ea98738"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "de7909b64bb66c887516f538e64decc7a52c29531ab6bb01f53eb2ec3557a773"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "dc02fc9546da6c49e2d0991e7bec98a465cd88e17a5ec9e2efc806f8f1d37003"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "31ac7e90238cee7ee04c0442ab8a3c2a8cf40f298cafb3f31118cbb36b2c4e4b"
metafile = true

[[files]]
file = "mods/ebe.toml"
hash = "72a4338b738c76967bd08f1aedb2f7760afa0de1dcdad352c9604363abe1a840"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "8783fffeefc606aeac7b1ca2b8aa2e7e6d7e31d956ff02af879ffb4fa9a5159e"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "767eea9287ca8b5f73fc9778d8fd653ebe8118bb8734c8b370bd255c262fd210"
metafile = true

[[files]]
file = "mods/figura.toml"
hash = "6522cd950b9b686e094c13ce9f5c69c1794dde79665659e06500270635bb213a"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "0e1a6f22d9e5538561be2f2a8bfd4998704124266c2af98d23e9adc67df5f9d9"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "2e64535aee940e97bfd8b494972547b8ae3c7e1785b16f4863c970d32aceb024"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "01f54d293d1008f22f8cfc9a43b4c8e5473d882c2ed7ca667cbcf55ae4d638bc"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "5a50deb77add78a3ad5f37c7ecf0cf3b4096c1359605b4082064ca978f080cdf"
metafile = true

[[files]]
file = "mods/op-items-tab.toml"
hash = "493cafa1d6a1d781a2062ac4757831d1514ea1229bd5501f9bedcbd8b2b4695b"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "d815ffd6112df95b8448fb22732937595d2df99bbde9160a31e58944640686ca"
metafile = true
