hash-format = "sha256"

[[files]]
file = "mods/bedrockskinutility.toml"
hash = "ead1756eb3ac87a7689a6abc45e99fa9da82c09dedb29a0becb00c0d67b9987c"
metafile = true

[[files]]
file = "mods/c2me-fabric.toml"
hash = "1c09ba69d8194333873125194bc49aa6fa90597f180b99fb37893747604e8079"
metafile = true

[[files]]
file = "mods/cem.toml"
hash = "9dff3a7a38420efbc6680d3073e3d79e417d48e51b172979b39941c00d23d027"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "03e734343ae43cadbf86e972990933f75342e4a3046956c9e4871fef1ddb6bee"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "642eedf14c0875215d1d15a39ecab4b1bfcec093e43626cb002f2c890f78c520"
metafile = true

[[files]]
file = "mods/debugify.toml"
hash = "9d5d339c329cb7e2a8c7540da5dff5e81cb99b769986c3f88fcfa17d21477f18"
metafile = true

[[files]]
file = "mods/ebe.toml"
hash = "c54828ea5dbf68713a260dec92054158ee4e9632a0288640ebe2275a369f9a62"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.toml"
hash = "b25b3e65687162fe6b6b880b945a2841c3f15d03afd3ff95f0d84eae3f7220f7"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "3c6d2d6aa83c3d0be1333c5015540630139c41890eb2cc483ef9f97ccc2c5cd3"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "f19e328fe42f91d1b65e244ee5bcf70f1e5305a27278945098ea85af82e05d0d"
metafile = true

[[files]]
file = "mods/gldown.toml"
hash = "2c427789543f276864e54ae8fbfcb58c09b67b19fae65eb36e19381c956df84b"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "735bb894e8fd0430de8fe331347ff24c5c64643bc65f2c040f7a82fb17e8b826"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "cbc3d6649757c3751ac73aed8df427b3ebc5685a808935b0e631d213bf6a760b"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "d609573e65a0c0417060648951d396133b295f172fa8f21ce6566d66d27e8320"
metafile = true

[[files]]
file = "mods/lazy-language-loader.toml"
hash = "6d4dc7f1d53a99efa4cf755fc08253a0d06128f7abccc603c86b37b05bae98e8"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "64a4b886ff13e45a06ae3714f4ec3fd5c15a1a4e0573df1cdfa35d673eec45ad"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "b5e2c3c08224e46e840c739f0b77bb22949373cc76d0ba90ddb22e52ecaa04c7"
metafile = true

[[files]]
file = "mods/puzzle.toml"
hash = "1754cb3e21a8732d329328a3ccc65e25977eb40e1d4f9ba4f3e57cb60bfd423a"
metafile = true

[[files]]
file = "mods/quilt-loading-screen.toml"
hash = "372dbd8b7394ee50d24298b092017689dbec5962658221d0bcc5ee492076d860"
metafile = true

[[files]]
file = "mods/raised.toml"
hash = "82bf62a035b5d56ac6f1da8e70f6e321e22edc7fc662e5f744e5414fed65a447"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "0c83c344046d0b96fd7dcd9e5c98c44caa3d307126d502f202dba50855304fb9"
metafile = true

[[files]]
file = "mods/spark.toml"
hash = "f3788c11d6e2da088378f7b2fa47dbf01da87bc13a34bf0dbafac24fbdbc6acb"
metafile = true
