hash-format = "sha256"

[[files]]
file = "mods/bedrockskinutility.toml"
hash = "606ffbce2be63253ec09ba3c496f6cc72e12cf54d031237bf82001910141d5dd"
metafile = true

[[files]]
file = "mods/custom-lan.toml"
hash = "cc54811d279f5ef07dbec15e3d82e12e9bda7090f419282dc1e1fdd3ff8f4756"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "92eab931314c02773c8466741e070791a94ade517298b49441b116e1c2da2a94"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "a861427308bb3d77c9ca0867e5cae8fed89b5eb3a08d0af9604be1e43e17fc28"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/no-telemetry.toml"
hash = "d893f12bb1254540fb7991c86d393bb73dc20d383d1dc091cde31219c9ef09dd"
metafile = true

[[files]]
file = "mods/plasmo-voice.toml"
hash = "6426492ed99683fdb47bef0457c0fd9e45af4791b0781a55f8beb5e86209bb62"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "55f39b31f37997e41e0578693103e50cebc79d4eee509801479cc50a75eeb347"
metafile = true
