hash-format = "sha256"

[[files]]
file = "mods/bedrockskinutility.toml"
hash = "ead1756eb3ac87a7689a6abc45e99fa9da82c09dedb29a0becb00c0d67b9987c"
metafile = true

[[files]]
file = "mods/c2me-fabric.toml"
hash = "1c09ba69d8194333873125194bc49aa6fa90597f180b99fb37893747604e8079"
metafile = true

[[files]]
file = "mods/cem.toml"
hash = "84736dff13eb506b1cedcdb7a359bb0af143b987696e382e7502591d51c65ac2"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "03e734343ae43cadbf86e972990933f75342e4a3046956c9e4871fef1ddb6bee"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "642eedf14c0875215d1d15a39ecab4b1bfcec093e43626cb002f2c890f78c520"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "59cedfbefe7c2657cdd674e3559235fbfcc16217266a6f70515c39c15b141f6c"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "263be2d355829560e28a8f8600de3beb98eec20d4f03b0ac78504991b947371c"
metafile = true

[[files]]
file = "mods/gldown.toml"
hash = "2c427789543f276864e54ae8fbfcb58c09b67b19fae65eb36e19381c956df84b"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "7215a34a544194eecb37e9bdfd9664edf21ac991f5a7b19c661e033975fe735f"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "89a1ad95dd9ccb136f9b995d9f63d8bc221a6e6acc3c8a596ab825ff46170186"
metafile = true

[[files]]
file = "mods/kappa.toml"
hash = "6363596c5cb5959ee0905e42c305b27934f169e634eaffc6ca268623c2410915"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "d609573e65a0c0417060648951d396133b295f172fa8f21ce6566d66d27e8320"
metafile = true

[[files]]
file = "mods/lazy-language-loader.toml"
hash = "6d4dc7f1d53a99efa4cf755fc08253a0d06128f7abccc603c86b37b05bae98e8"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "64a4b886ff13e45a06ae3714f4ec3fd5c15a1a4e0573df1cdfa35d673eec45ad"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "b5e2c3c08224e46e840c739f0b77bb22949373cc76d0ba90ddb22e52ecaa04c7"
metafile = true

[[files]]
file = "mods/puzzle.toml"
hash = "1754cb3e21a8732d329328a3ccc65e25977eb40e1d4f9ba4f3e57cb60bfd423a"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "0c83c344046d0b96fd7dcd9e5c98c44caa3d307126d502f202dba50855304fb9"
metafile = true

[[files]]
file = "mods/spark.toml"
hash = "876706fed00aa097c8a72fa378f225321aa886658001d679355d784a2772e0de"
metafile = true
