hash-format = "sha256"

[[files]]
file = "mods/animatica.toml"
hash = "0f832605c4764af1bf759fd26fb11bbe23b9eb3580f75a8999d5431a0ea98738"
metafile = true

[[files]]
file = "mods/c2me-fabric.toml"
hash = "096701116a96d58aa1a1799f8d56039443b7cc1064589e68d733045d2aecface"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "de7909b64bb66c887516f538e64decc7a52c29531ab6bb01f53eb2ec3557a773"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "dc02fc9546da6c49e2d0991e7bec98a465cd88e17a5ec9e2efc806f8f1d37003"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "31ac7e90238cee7ee04c0442ab8a3c2a8cf40f298cafb3f31118cbb36b2c4e4b"
metafile = true

[[files]]
file = "mods/ebe.toml"
hash = "72a4338b738c76967bd08f1aedb2f7760afa0de1dcdad352c9604363abe1a840"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "ed7cd7a11952155583a80c1b54231b84e5b26e1c8642304469a3d20d5f6b7ed3"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "767eea9287ca8b5f73fc9778d8fd653ebe8118bb8734c8b370bd255c262fd210"
metafile = true

[[files]]
file = "mods/figura.toml"
hash = "6522cd950b9b686e094c13ce9f5c69c1794dde79665659e06500270635bb213a"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "0e1a6f22d9e5538561be2f2a8bfd4998704124266c2af98d23e9adc67df5f9d9"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "2b199deceff30e132074d9850f16e5ff990808eabf36a5ba95af0f521a2eb85f"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "01f54d293d1008f22f8cfc9a43b4c8e5473d882c2ed7ca667cbcf55ae4d638bc"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "e1aea49ed8a6f2af853793ee649e69d27d872b080c4a4a30264a42022a4eabed"
metafile = true

[[files]]
file = "mods/plasmo-voice.toml"
hash = "168ad4b92ff8527130a1c0bf337c5e4867debb41a6fc06f2fa2cbc46f0b358a4"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "a0fa129729bb5d0ed3419558d2819116cc0b9d055f5f356c165207ab1762f89d"
metafile = true

[[files]]
file = "mods/starlight.toml"
hash = "cb9176439af93f4215bc9eb96ddcfa02566ea41aa5c1b6e230a66bfd23299255"
metafile = true
