name = "Piuvas Packwiz"
author = "piuvas"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6900c7ea728adda19c1f4dd809251ac088fa379402c21de281628dda182b99d9"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
