name = "piuvaspackwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "101305664ea293c9050f2a9563c9351702accba772c8a2a0f6d722dd3eca3778"

[versions]
fabric = "0.12.3"
minecraft = "1.17.1"
