name = "piuvaspackwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77b47aaac4dc55cf00b3f791d2f378ecd14564b13479ef4179ea733facac2e27"

[versions]
fabric = "0.12.3"
minecraft = "1.17.1"
