name = "Piuvas Packwiz"
author = "piuvas"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37de3bb4ec244604134d50dfc9d1848a6437490d174483276ad86f71cef9ec84"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
