name = "Piuvas Packwiz"
author = "piuvas"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab225f7f79c10e6bcb7469f22c67986fa120d05c59d6569a9fe500d467cf2576"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
