name = "Piuvas Packwiz"
author = "piuvas"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "102a02f65e047ea1339265f5e610aacc02fff1110b457e00667a7247385cc160"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
