name = "Piuvas Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b29bf4abaf44a278e640a84704548c0f0453f5864358b702f649da6a23a98a6"

[versions]
fabric = "0.12.6"
minecraft = "1.18"
