name = "Piuvas Packwiz"
author = "piuvas"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37bfff80f8d9a2a207afb100145ac3a2c66a88a1ef98aae8fcdde75194a81b27"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
