name = "Piuvas Packwiz"
author = "piuvas"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72746d75bb00f60f7af9ccea0d23d36d22c500b1f45136baa31ceb88e35cdda7"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
