name = "Piuvas Packwiz"
author = "piuvas"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2109c20b7c6fc7827a300090c978de616d73cd234fc4a7a41cc9ed3a3aa1d8a8"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
