name = "Piuvas Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72c8630b6073f513da0fa97c5ec0f9718daa584bfaa71d81075c7800a6e60eec"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
