name = "Piuvas Packwiz"
author = "piuvas"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95de8dbd0679fa854456e2ddf0d77bafe81837a4b38fd86dfe2684a5eeb77c3d"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
