name = "Piuvas Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d541814a520a24311dae07b2157585593c4699af32cb285e22139eab03d0cdc"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
