name = "piuvaspackwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "641e17e76938d55f97416626ecc8fdf0fd108bab5cbdf4bb37c826631e12de74"

[versions]
fabric = "0.12.3"
minecraft = "1.17.1"
