name = "Piuvas Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "485ed1e1ca08925fc4bdced3654f6de1eeae6d68b8ebe936fa0a7a5fa560f729"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
