name = "Piuvas Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea02e32fb7d49dba048a56a97f59b536bf99ecf54cd11c1df7e16f0d55db9318"

[versions]
fabric = "0.12.6"
minecraft = "1.18"
