name = "BedrockSkinUtility"
filename = "BedrockSkinUtility-1.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/ihxXgVk3/versions/1.2/BedrockSkinUtility-1.2.jar"
hash-format = "sha512"
hash = "56a088c88bf034773cafd7c5cede41c263de9eb5f03982e72de1d226f28f9e0fb4bd9c6696f6654d9dfc7f107168ef3f729994f0301dde9c8287913a14b40669"

[update]
[update.modrinth]
mod-id = "ihxXgVk3"
version = "LRld6SO5"
