name = "Custom Entity Models"
filename = "cem-0.7.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YOQCucah/versions/0.7.0/cem-0.7.0.jar"
hash-format = "sha512"
hash = "731ed8b4167806c0db0b6e780d918923787024dc65853d880c78d5a1ce2166bd28e895c4ff1b7d07befb25c1ebcc09ffc55e62ae7e64845e17a2ab6dfc5062a3"

[update]
[update.modrinth]
mod-id = "YOQCucah"
version = "Z42auxMF"
