name = "Custom LAN"
filename = "custom-lan-1.18-v2.0.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/OCvCFPNR/versions/1.18-v2.0.1/custom-lan-1.18-v2.0.1.jar"
hash-format = "sha512"
hash = "dc5e6ede149df2d50aae445c32aaa24af42a41dfd267fe08c541d6ce5b5ebc936f7ba789def7b4cbbc6bcb8254041a0681ada1ac886434c78b93bda2592e4889"

[update]
[update.modrinth]
mod-id = "OCvCFPNR"
version = "jtEOcbwc"
