name = "Debugify"
filename = "debugify-fabric-1.7.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/QwxR6Gcd/versions/1.7.1-fabric/debugify-fabric-1.7.1.jar"
hash-format = "sha512"
hash = "5f61556639be476ebfc7e24e04717b9c3abdf56f238d432a818a59e93316601564296de5ba6415f48e0ead844a1a58ffbb314075ac23337acf8752aba7ae9f10"

[update]
[update.modrinth]
mod-id = "QwxR6Gcd"
version = "hY3DKYio"
