name = "Debugify"
filename = "debugify-fabric-1.7.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/QwxR6Gcd/versions/1.7.2-fabric/debugify-fabric-1.7.2.jar"
hash-format = "sha512"
hash = "d48cab2a564975e2577cd8a7e1ae0b83c902394381b95a411e39146fe02fa6a733dfb771559dc26860f263d0f8e4e83e81ec57317521156f3104748b6defe506"

[update]
[update.modrinth]
mod-id = "QwxR6Gcd"
version = "CSWmF24f"
