name = "Enhanced Block Entities"
filename = "enhancedblockentities-0.6+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/OVuFYfre/versions/0.6+1.18.2/enhancedblockentities-0.6%2B1.18.2.jar"
hash-format = "sha512"
hash = "fad866d1a1abae275b3c0bbd9003b228a2006262e23cc20f0a22b22d830b82a261b2cb8255377910f6fe2e44de87ae54a92f18021988ad3cca7c08f176a97b7c"

[update]
[update.modrinth]
mod-id = "OVuFYfre"
version = "VOB3iJkd"
