name = "Fabric API"
filename = "fabric-api-0.47.9+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.47.9+1.18.2/fabric-api-0.47.9%2B1.18.2.jar"
hash-format = "sha512"
hash = "11d9639a2f577ecdc80ace8423d13c2d9a792702f3ae7be011e24623f6ee64b368849b636b27f524a6b49c38dc007eae332c9c1845c509a54551ab6d5d251694"

[update]
[update.modrinth]
mod-id = "P7dR8mSH"
version = "mGIxWbTy"
