name = "Fabric API"
filename = "fabric-api-0.51.1+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.51.1+1.18.2/fabric-api-0.51.1%2B1.18.2.jar"
hash-format = "sha512"
hash = "776ab0040524da85f0ae77a1047b8c49938282cae52f188e84aa4c3be4bbc4ebbe69ac3c1db248ceb1550164f37c1128b08f6ada87ee8ab243a073fc3b077c92"

[update]
[update.modrinth]
mod-id = "P7dR8mSH"
version = "VO0pdfjT"
