name = "Fabric API"
filename = "fabric-api-0.51.0+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.51.0+1.18.2/fabric-api-0.51.0%2B1.18.2.jar"
hash-format = "sha512"
hash = "652de9efa07e2e06cea64f16a790c453c31a398d1f0430dac42c033b3951c36dd6e1ada666601a10c139fdd62bf62773ba2ef764146e1e3165d077c21832c4af"

[update]
[update.modrinth]
mod-id = "P7dR8mSH"
version = "GxqbUxtc"
