name = "Fabric API"
filename = "fabric-api-0.45.1+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.45.1+1.18/fabric-api-0.45.1+1.18.jar"
hash-format = "sha512"
hash = "9f450a8e93b7831dbee0368758e408858cff66a706828536c65232909626046bf49ed578fe21b43cbf154930ebf59c62b98cf072899504dd18b1f5e029aadc0b"

[update]
[update.modrinth]
mod-id = "P7dR8mSH"
version = "qN4IdGPY"
