name = "Fabric API"
filename = "fabric-api-0.43.0+1.17.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.43.0+1.17/fabric-api-0.43.0+1.17.jar"
hash-format = "sha512"
hash = "53d054820b41417cf8a9fcfaa068c499247206c3a919970c5024b18174e67860f17e8fb0198258297760bfd97af130f33bf12e9b917c71a518c5499f1f6058b0"

[update]
[update.modrinth]
mod-id = "P7dR8mSH"
version = "2ZVOAfTp"
