name = "lazy-language-loader"
filename = "lazy-language-loader-0.2.4.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/Nz0RSWrF/versions/0.2.4/lazy-language-loader-0.2.4.jar"
hash-format = "sha512"
hash = "86d5c5298319672500fbf6e4f557c56ec98182b8f6aa555207b57781414d72a972d80d342e88d7767e70e32067f69b312a260c5a37d9a5b383916552a7bd9124"

[update]
[update.modrinth]
mod-id = "Nz0RSWrF"
version = "gbbefmHf"
