name = "Op Items Tab"
filename = "opitems-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3344/584/opitems-1.2.0.jar"
hash-format = "murmur2"
hash = "159838241"

[update]
[update.curseforge]
file-id = 3344584
project-id = 441383
