name = "Plasmo Voice"
filename = "plasmovoice-fabric-1.17.1-1.2.7.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/1bZhdhsH/versions/fabric-1.17.1-1.2.7/plasmovoice-fabric-1.17.1-1.2.7.jar"
hash-format = "sha512"
hash = "332d2b587b23b4df27c45db29a70d00b0a8a4c69c1267fd83e6ac97d140d059095739e84ea5568c4556ed1af22954c63e43b2acdc82f92adc87ee80b965969c0"

[update]
[update.modrinth]
mod-id = "1bZhdhsH"
version = "zlQbC0Oq"
