name = "Raised"
filename = "raised-fabric-1.18.2-1.0.6.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/nCQRBEiR/versions/Fabric-1.18.2-1.0.6/raised-fabric-1.18.2-1.0.6.jar"
hash-format = "sha512"
hash = "fd46f3ff367b988ae6cdce4f5ace064f02c900e8a132bb7e1976dfc457ff488cd3841d2162a867f921b9147bc6a063dc9cd2188d36f446046152f3905b2b28b7"

[update]
[update.modrinth]
mod-id = "nCQRBEiR"
version = "EM4xqghR"
