name = "Raised"
filename = "raised-fabric-1.18.2-1.0.7.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/nCQRBEiR/versions/Fabric-1.18.2-1.0.7/raised-fabric-1.18.2-1.0.7.jar"
hash-format = "sha512"
hash = "571746d28a1ea210b9a0325802c2b8fa4a5975346555067de64e5b8f28ae5bff5fb4042388b3a08103d76b969b7d46f22b83c8c38f9a720dcffe28a8ff205396"

[update]
[update.modrinth]
mod-id = "nCQRBEiR"
version = "e7P9ftjJ"
