name = "spark"
filename = "spark-1.8.14-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/l6YH9Als/versions/1.8.14-fabric/spark-1.8.14-fabric.jar"
hash-format = "sha512"
hash = "f15ad7bc9f423ff507721ac1059df31dcb1211a488e61088f29467bc083eeb34bb1b126a39219a46a6e9711772f7384e254999181fdbfce3c7edec33f5be64fb"

[update]
[update.modrinth]
mod-id = "l6YH9Als"
version = "VkKsarbC"
